name: magg

services:
  base:
    profiles: ["_"]  # Hidden from normal operations
    build:
      dockerfile: dockerfile
      args:
        MAGG_READ_ONLY: ${MAGG_READ_ONLY:-false}
    environment:
      MAGG_PRIVATE_KEY: ${MAGG_PRIVATE_KEY:-}
      MAGG_LOG_LEVEL: ${MAGG_LOG_LEVEL:-}
      MAGG_CONFIG_PATH: ${MAGG_CONFIG_PATH:-}
      MAGG_SELF_PREFIX: ${MAGG_SELF_PREFIX:-}
      MAGG_AUTO_RELOAD: ${MAGG_AUTO_RELOAD:-false}
      MAGG_RELOAD_POLL_INTERVAL: ${MAGG_RELOAD_POLL_INTERVAL:-}
      MAGG_RELOAD_USE_WATCHDOG: ${MAGG_RELOAD_USE_WATCHDOG:-}
      MAGG_STDERR_SHOW: ${MAGG_STDERR_SHOW:-}
      MAGG_PREFIX_SEP: ${MAGG_PREFIX_SEP:-}
      MAGG_SSL_KEYFILE: ${MAGG_SSL_KEYFILE:-}
      MAGG_SSL_CERTFILE: ${MAGG_SSL_CERTFILE:-}
    volumes:
      - ${MAGG_CONFIG_VOLUME:-magg-config}:/home/magg/.magg
      # Legacy directory mount for backward compatibility
      - ${MAGG_SSL_CERTS_PATH:-./certs}:/certs:ro
      # For host path SSL certificates, use compose.ssl.yaml overlay:
      # docker compose -f compose.yaml -f compose.ssl.yaml up
    networks:
      - magg-network
    restart: unless-stopped

  magg:
    extends:
      service: base
    build:
      target: pro
    image: ${REGISTRY:-}${REGISTRY:+/}magg:${SOURCE:-${USER}}-pro
    container_name: magg-server
    ports:
      - "8000:8000"

  magg-beta:
    extends:
      service: base
    build:
      target: pre
    image: ${REGISTRY:-}${REGISTRY:+/}magg:${SOURCE:-${USER}}-pre
    container_name: magg-server-pre
    ports:
      - "8001:8000"

  magg-dev:
    extends:
      service: base
    build:
      target: dev
    environment:
      MAGG_AUTO_RELOAD: ${MAGG_AUTO_RELOAD:-true}
    image: ${REGISTRY:-}${REGISTRY:+/}magg:${SOURCE:-${USER}}-dev
    container_name: magg-server-dev
    ports:
      - "8008:8000"
    volumes:
      - ./.magg:/home/magg/.magg:rw
      # Legacy directory mount for backward compatibility
      - ${MAGG_SSL_CERTS_PATH:-./certs}:/certs:ro
      # For host path SSL certificates, use compose.ssl.yaml overlay:
      # docker compose -f compose.yaml -f compose.ssl.yaml up

volumes:
  magg-config:

networks:
  magg-network:
    driver: bridge
